stages:
    - build
    - test
    - cleanup

make:
    stage: build
    script:
        - ls
        - mkdir build
        - ls
        - cd build
        - cmake -DCMAKE_BUILD_TYPE=Debug ..
        - make
        - cd ..
    cache:
        key: "$CI_COMMIT_REF_SLUG"
        paths:
            - build/vendor/
        policy: pull-push
    tags:
        - "clang-6.0"
        - "cmake"

tester:
    stage: test
    script:
        - ls
        - cd build/test/unitTest
        - ./test_surf_ints

lint:
    stage: test
    script:
        - mkdir -p build
        - cd build
        - cmake -DCMAKE_BUILD_TYPE=Debug ..
        - make lint
    cache:
        key: "$CI_COMMIT_REF_SLUG"
        paths:
            - build/vendor/
        policy: pull-push
    tags:
        - "clang-6.0"
        - "clang-tidy-6.0"
        - "cmake"
        - "python3"
    allow_failure: true
